import vanishinghalf2 from '../../assets/images/vanishinghalf2.jpeg';
import thepush from '../../assets/images/thepush.jpeg';
import midnightlibrary from '../../assets/images/midnightlibrary.jpeg';
import actsofdesperation from '../../assets/images/actsofdesperation.jpeg';
import fourwinds from '../../assets/images/fourwinds.jpeg';
import bloodandash from '../../assets/images/bloodandash.jpeg';
import thegreatalone from '../../assets/images/thegreatalone.jpeg';

const blogPosts = [
  {
    id: 1,
    title: 'The Vanishing Half',
    author: 'Brit Bennett',
    genre: 'Fiction',
    image: vanishinghalf2,
    summary:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ut ante dapibus risus lobortis interdum. Nam risus eros, ullamcorper id arcu a, convallis dapibus nisl. Etiam vulputate pharetra diam, sit amet luctus libero sollicitudin vitae. Integer lacus metus, pretium quis suscipit nec, mollis sit amet velit. Suspendisse purus arcu, accumsan dapibus libero at, dignissim posuere leo. Vivamus eu volutpat velit, nec accumsan ipsum. Suspendisse sit amet malesuada nunc. Sed sapien urna, euismod interdum nunc a, iaculis porttitor augue. Aliquam posuere feugiat arcu et eleifend. Phasellus feugiat neque finibus diam fringilla facilisis. Phasellus vitae congue nisi. Mauris hendrerit massa eros, sed pharetra erat vulputate eu. Morbi placerat purus ac aliquam pretium. In efficitur tincidunt fermentum. Phasellus vitae ante nibh. Pellentesque tempor ornare dui, ut ullamcorper nulla ullamcorper a. Mauris elementum condimentum est quis posuere. Quisque posuere nibh arcu, vel blandit mi iaculis vitae. Pellentesque augue lorem, malesuada feugiat suscipit eget, ornare eget felis. Ut pharetra vel massa vel faucibus. Aliquam blandit, leo et tristique sagittis, elit odio dignissim orci, non commodo lacus leo a ex. Maecenas massa velit, efficitur a suscipit sit amet, hendrerit vel mi. Aenean tempus rutrum venenatis. Proin id efficitur elit. Sed efficitur commodo dui, id pretium lorem fermentum ut. Nullam lacinia, dolor quis blandit egestas, magna leo pharetra lacus, vel interdum lectus orci dignissim tellus. Vestibulum iaculis maximus felis, eu sollicitudin nisl dictum non. Aliquam erat volutpat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi fringilla est eget ultrices tempor. Proin interdum lacus ac sollicitudin eleifend. Duis ac erat non turpis tempor aliquet vitae dignissim dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec eu placerat neque. Sed sed dolor ornare elit consectetur semper nec in ex. Curabitur sit amet orci elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  },
  {
    id: 2,
    title: 'The Push',
    author: 'Ashley Audrain',
    genre: 'Fiction',
    image: thepush,
    summary:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ut ante dapibus risus lobortis interdum. Nam risus eros, ullamcorper id arcu a, convallis dapibus nisl. Etiam vulputate pharetra diam, sit amet luctus libero sollicitudin vitae. Integer lacus metus, pretium quis suscipit nec, mollis sit amet velit. Suspendisse purus arcu, accumsan dapibus libero at, dignissim posuere leo. Vivamus eu volutpat velit, nec accumsan ipsum. Suspendisse sit amet malesuada nunc. Sed sapien urna, euismod interdum nunc a, iaculis porttitor augue. Aliquam posuere feugiat arcu et eleifend. Phasellus feugiat neque finibus diam fringilla facilisis. Phasellus vitae congue nisi. Mauris hendrerit massa eros, sed pharetra erat vulputate eu. Morbi placerat purus ac aliquam pretium. In efficitur tincidunt fermentum. Phasellus vitae ante nibh. Pellentesque tempor ornare dui, ut ullamcorper nulla ullamcorper a. Mauris elementum condimentum est quis posuere. Quisque posuere nibh arcu, vel blandit mi iaculis vitae. Pellentesque augue lorem, malesuada feugiat suscipit eget, ornare eget felis. Ut pharetra vel massa vel faucibus. Aliquam blandit, leo et tristique sagittis, elit odio dignissim orci, non commodo lacus leo a ex. Maecenas massa velit, efficitur a suscipit sit amet, hendrerit vel mi. Aenean tempus rutrum venenatis. Proin id efficitur elit. Sed efficitur commodo dui, id pretium lorem fermentum ut. Nullam lacinia, dolor quis blandit egestas, magna leo pharetra lacus, vel interdum lectus orci dignissim tellus. Vestibulum iaculis maximus felis, eu sollicitudin nisl dictum non. Aliquam erat volutpat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi fringilla est eget ultrices tempor. Proin interdum lacus ac sollicitudin eleifend. Duis ac erat non turpis tempor aliquet vitae dignissim dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec eu placerat neque. Sed sed dolor ornare elit consectetur semper nec in ex. Curabitur sit amet orci elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  },
  {
    id: 3,
    title: 'The Midnight Library',
    author: 'Ashley Audrain',
    genre: 'Fiction',
    image: midnightlibrary,
    summary:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ut ante dapibus risus lobortis interdum. Nam risus eros, ullamcorper id arcu a, convallis dapibus nisl. Etiam vulputate pharetra diam, sit amet luctus libero sollicitudin vitae. Integer lacus metus, pretium quis suscipit nec, mollis sit amet velit. Suspendisse purus arcu, accumsan dapibus libero at, dignissim posuere leo. Vivamus eu volutpat velit, nec accumsan ipsum. Suspendisse sit amet malesuada nunc. Sed sapien urna, euismod interdum nunc a, iaculis porttitor augue. Aliquam posuere feugiat arcu et eleifend. Phasellus feugiat neque finibus diam fringilla facilisis. Phasellus vitae congue nisi. Mauris hendrerit massa eros, sed pharetra erat vulputate eu. Morbi placerat purus ac aliquam pretium. In efficitur tincidunt fermentum. Phasellus vitae ante nibh. Pellentesque tempor ornare dui, ut ullamcorper nulla ullamcorper a. Mauris elementum condimentum est quis posuere. Quisque posuere nibh arcu, vel blandit mi iaculis vitae. Pellentesque augue lorem, malesuada feugiat suscipit eget, ornare eget felis. Ut pharetra vel massa vel faucibus. Aliquam blandit, leo et tristique sagittis, elit odio dignissim orci, non commodo lacus leo a ex. Maecenas massa velit, efficitur a suscipit sit amet, hendrerit vel mi. Aenean tempus rutrum venenatis. Proin id efficitur elit. Sed efficitur commodo dui, id pretium lorem fermentum ut. Nullam lacinia, dolor quis blandit egestas, magna leo pharetra lacus, vel interdum lectus orci dignissim tellus. Vestibulum iaculis maximus felis, eu sollicitudin nisl dictum non. Aliquam erat volutpat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi fringilla est eget ultrices tempor. Proin interdum lacus ac sollicitudin eleifend. Duis ac erat non turpis tempor aliquet vitae dignissim dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec eu placerat neque. Sed sed dolor ornare elit consectetur semper nec in ex. Curabitur sit amet orci elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  },
  {
    id: 4,
    title: 'Acts of Desperation',
    author: 'Megan Nolan',
    genre: 'Fiction',
    image: actsofdesperation,
    summary:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ut ante dapibus risus lobortis interdum. Nam risus eros, ullamcorper id arcu a, convallis dapibus nisl. Etiam vulputate pharetra diam, sit amet luctus libero sollicitudin vitae. Integer lacus metus, pretium quis suscipit nec, mollis sit amet velit. Suspendisse purus arcu, accumsan dapibus libero at, dignissim posuere leo. Vivamus eu volutpat velit, nec accumsan ipsum. Suspendisse sit amet malesuada nunc. Sed sapien urna, euismod interdum nunc a, iaculis porttitor augue. Aliquam posuere feugiat arcu et eleifend. Phasellus feugiat neque finibus diam fringilla facilisis. Phasellus vitae congue nisi. Mauris hendrerit massa eros, sed pharetra erat vulputate eu. Morbi placerat purus ac aliquam pretium. In efficitur tincidunt fermentum. Phasellus vitae ante nibh. Pellentesque tempor ornare dui, ut ullamcorper nulla ullamcorper a. Mauris elementum condimentum est quis posuere. Quisque posuere nibh arcu, vel blandit mi iaculis vitae. Pellentesque augue lorem, malesuada feugiat suscipit eget, ornare eget felis. Ut pharetra vel massa vel faucibus. Aliquam blandit, leo et tristique sagittis, elit odio dignissim orci, non commodo lacus leo a ex. Maecenas massa velit, efficitur a suscipit sit amet, hendrerit vel mi. Aenean tempus rutrum venenatis. Proin id efficitur elit. Sed efficitur commodo dui, id pretium lorem fermentum ut. Nullam lacinia, dolor quis blandit egestas, magna leo pharetra lacus, vel interdum lectus orci dignissim tellus. Vestibulum iaculis maximus felis, eu sollicitudin nisl dictum non. Aliquam erat volutpat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi fringilla est eget ultrices tempor. Proin interdum lacus ac sollicitudin eleifend. Duis ac erat non turpis tempor aliquet vitae dignissim dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec eu placerat neque. Sed sed dolor ornare elit consectetur semper nec in ex. Curabitur sit amet orci elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  },
  {
    id: 5,
    title: 'The Four Winds',
    author: 'Kristin Hannah',
    genre: 'Fiction',
    image: fourwinds,
    summary:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ut ante dapibus risus lobortis interdum. Nam risus eros, ullamcorper id arcu a, convallis dapibus nisl. Etiam vulputate pharetra diam, sit amet luctus libero sollicitudin vitae. Integer lacus metus, pretium quis suscipit nec, mollis sit amet velit. Suspendisse purus arcu, accumsan dapibus libero at, dignissim posuere leo. Vivamus eu volutpat velit, nec accumsan ipsum. Suspendisse sit amet malesuada nunc. Sed sapien urna, euismod interdum nunc a, iaculis porttitor augue. Aliquam posuere feugiat arcu et eleifend. Phasellus feugiat neque finibus diam fringilla facilisis. Phasellus vitae congue nisi. Mauris hendrerit massa eros, sed pharetra erat vulputate eu. Morbi placerat purus ac aliquam pretium. In efficitur tincidunt fermentum. Phasellus vitae ante nibh. Pellentesque tempor ornare dui, ut ullamcorper nulla ullamcorper a. Mauris elementum condimentum est quis posuere. Quisque posuere nibh arcu, vel blandit mi iaculis vitae. Pellentesque augue lorem, malesuada feugiat suscipit eget, ornare eget felis. Ut pharetra vel massa vel faucibus. Aliquam blandit, leo et tristique sagittis, elit odio dignissim orci, non commodo lacus leo a ex. Maecenas massa velit, efficitur a suscipit sit amet, hendrerit vel mi. Aenean tempus rutrum venenatis. Proin id efficitur elit. Sed efficitur commodo dui, id pretium lorem fermentum ut. Nullam lacinia, dolor quis blandit egestas, magna leo pharetra lacus, vel interdum lectus orci dignissim tellus. Vestibulum iaculis maximus felis, eu sollicitudin nisl dictum non. Aliquam erat volutpat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi fringilla est eget ultrices tempor. Proin interdum lacus ac sollicitudin eleifend. Duis ac erat non turpis tempor aliquet vitae dignissim dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec eu placerat neque. Sed sed dolor ornare elit consectetur semper nec in ex. Curabitur sit amet orci elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  },
  {
    id: 6,
    title: 'From Blood and Ash',
    author: 'Jennifer L. Armentrout',
    genre: 'Fantasy',
    image: bloodandash,
    summary:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ut ante dapibus risus lobortis interdum. Nam risus eros, ullamcorper id arcu a, convallis dapibus nisl. Etiam vulputate pharetra diam, sit amet luctus libero sollicitudin vitae. Integer lacus metus, pretium quis suscipit nec, mollis sit amet velit. Suspendisse purus arcu, accumsan dapibus libero at, dignissim posuere leo. Vivamus eu volutpat velit, nec accumsan ipsum. Suspendisse sit amet malesuada nunc. Sed sapien urna, euismod interdum nunc a, iaculis porttitor augue. Aliquam posuere feugiat arcu et eleifend. Phasellus feugiat neque finibus diam fringilla facilisis. Phasellus vitae congue nisi. Mauris hendrerit massa eros, sed pharetra erat vulputate eu. Morbi placerat purus ac aliquam pretium. In efficitur tincidunt fermentum. Phasellus vitae ante nibh. Pellentesque tempor ornare dui, ut ullamcorper nulla ullamcorper a. Mauris elementum condimentum est quis posuere. Quisque posuere nibh arcu, vel blandit mi iaculis vitae. Pellentesque augue lorem, malesuada feugiat suscipit eget, ornare eget felis. Ut pharetra vel massa vel faucibus. Aliquam blandit, leo et tristique sagittis, elit odio dignissim orci, non commodo lacus leo a ex. Maecenas massa velit, efficitur a suscipit sit amet, hendrerit vel mi. Aenean tempus rutrum venenatis. Proin id efficitur elit. Sed efficitur commodo dui, id pretium lorem fermentum ut. Nullam lacinia, dolor quis blandit egestas, magna leo pharetra lacus, vel interdum lectus orci dignissim tellus. Vestibulum iaculis maximus felis, eu sollicitudin nisl dictum non. Aliquam erat volutpat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi fringilla est eget ultrices tempor. Proin interdum lacus ac sollicitudin eleifend. Duis ac erat non turpis tempor aliquet vitae dignissim dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec eu placerat neque. Sed sed dolor ornare elit consectetur semper nec in ex. Curabitur sit amet orci elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  },
  {
    id: 7,
    title: 'The Great Alone',
    author: 'Kristin Hannah',
    genre: 'Fiction',
    image: thegreatalone,
    summary:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ut ante dapibus risus lobortis interdum. Nam risus eros, ullamcorper id arcu a, convallis dapibus nisl. Etiam vulputate pharetra diam, sit amet luctus libero sollicitudin vitae. Integer lacus metus, pretium quis suscipit nec, mollis sit amet velit. Suspendisse purus arcu, accumsan dapibus libero at, dignissim posuere leo. Vivamus eu volutpat velit, nec accumsan ipsum. Suspendisse sit amet malesuada nunc. Sed sapien urna, euismod interdum nunc a, iaculis porttitor augue. Aliquam posuere feugiat arcu et eleifend. Phasellus feugiat neque finibus diam fringilla facilisis. Phasellus vitae congue nisi. Mauris hendrerit massa eros, sed pharetra erat vulputate eu. Morbi placerat purus ac aliquam pretium. In efficitur tincidunt fermentum. Phasellus vitae ante nibh. Pellentesque tempor ornare dui, ut ullamcorper nulla ullamcorper a. Mauris elementum condimentum est quis posuere. Quisque posuere nibh arcu, vel blandit mi iaculis vitae. Pellentesque augue lorem, malesuada feugiat suscipit eget, ornare eget felis. Ut pharetra vel massa vel faucibus. Aliquam blandit, leo et tristique sagittis, elit odio dignissim orci, non commodo lacus leo a ex. Maecenas massa velit, efficitur a suscipit sit amet, hendrerit vel mi. Aenean tempus rutrum venenatis. Proin id efficitur elit. Sed efficitur commodo dui, id pretium lorem fermentum ut. Nullam lacinia, dolor quis blandit egestas, magna leo pharetra lacus, vel interdum lectus orci dignissim tellus. Vestibulum iaculis maximus felis, eu sollicitudin nisl dictum non. Aliquam erat volutpat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi fringilla est eget ultrices tempor. Proin interdum lacus ac sollicitudin eleifend. Duis ac erat non turpis tempor aliquet vitae dignissim dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec eu placerat neque. Sed sed dolor ornare elit consectetur semper nec in ex. Curabitur sit amet orci elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  },
  {
    id: 8,
    title: 'The Midnight Library',
    author: 'Ashley Audrain',
    genre: 'Fiction',
    image: midnightlibrary,
    summary:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ut ante dapibus risus lobortis interdum. Nam risus eros, ullamcorper id arcu a, convallis dapibus nisl. Etiam vulputate pharetra diam, sit amet luctus libero sollicitudin vitae. Integer lacus metus, pretium quis suscipit nec, mollis sit amet velit. Suspendisse purus arcu, accumsan dapibus libero at, dignissim posuere leo. Vivamus eu volutpat velit, nec accumsan ipsum. Suspendisse sit amet malesuada nunc. Sed sapien urna, euismod interdum nunc a, iaculis porttitor augue. Aliquam posuere feugiat arcu et eleifend. Phasellus feugiat neque finibus diam fringilla facilisis. Phasellus vitae congue nisi. Mauris hendrerit massa eros, sed pharetra erat vulputate eu. Morbi placerat purus ac aliquam pretium. In efficitur tincidunt fermentum. Phasellus vitae ante nibh. Pellentesque tempor ornare dui, ut ullamcorper nulla ullamcorper a. Mauris elementum condimentum est quis posuere. Quisque posuere nibh arcu, vel blandit mi iaculis vitae. Pellentesque augue lorem, malesuada feugiat suscipit eget, ornare eget felis. Ut pharetra vel massa vel faucibus. Aliquam blandit, leo et tristique sagittis, elit odio dignissim orci, non commodo lacus leo a ex. Maecenas massa velit, efficitur a suscipit sit amet, hendrerit vel mi. Aenean tempus rutrum venenatis. Proin id efficitur elit. Sed efficitur commodo dui, id pretium lorem fermentum ut. Nullam lacinia, dolor quis blandit egestas, magna leo pharetra lacus, vel interdum lectus orci dignissim tellus. Vestibulum iaculis maximus felis, eu sollicitudin nisl dictum non. Aliquam erat volutpat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi fringilla est eget ultrices tempor. Proin interdum lacus ac sollicitudin eleifend. Duis ac erat non turpis tempor aliquet vitae dignissim dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec eu placerat neque. Sed sed dolor ornare elit consectetur semper nec in ex. Curabitur sit amet orci elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  },
  {
    id: 9,
    title: 'The Midnight Library',
    author: 'Ashley Audrain',
    genre: 'Fiction',
    image: midnightlibrary,
    summary:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ut ante dapibus risus lobortis interdum. Nam risus eros, ullamcorper id arcu a, convallis dapibus nisl. Etiam vulputate pharetra diam, sit amet luctus libero sollicitudin vitae. Integer lacus metus, pretium quis suscipit nec, mollis sit amet velit. Suspendisse purus arcu, accumsan dapibus libero at, dignissim posuere leo. Vivamus eu volutpat velit, nec accumsan ipsum. Suspendisse sit amet malesuada nunc. Sed sapien urna, euismod interdum nunc a, iaculis porttitor augue. Aliquam posuere feugiat arcu et eleifend. Phasellus feugiat neque finibus diam fringilla facilisis. Phasellus vitae congue nisi. Mauris hendrerit massa eros, sed pharetra erat vulputate eu. Morbi placerat purus ac aliquam pretium. In efficitur tincidunt fermentum. Phasellus vitae ante nibh. Pellentesque tempor ornare dui, ut ullamcorper nulla ullamcorper a. Mauris elementum condimentum est quis posuere. Quisque posuere nibh arcu, vel blandit mi iaculis vitae. Pellentesque augue lorem, malesuada feugiat suscipit eget, ornare eget felis. Ut pharetra vel massa vel faucibus. Aliquam blandit, leo et tristique sagittis, elit odio dignissim orci, non commodo lacus leo a ex. Maecenas massa velit, efficitur a suscipit sit amet, hendrerit vel mi. Aenean tempus rutrum venenatis. Proin id efficitur elit. Sed efficitur commodo dui, id pretium lorem fermentum ut. Nullam lacinia, dolor quis blandit egestas, magna leo pharetra lacus, vel interdum lectus orci dignissim tellus. Vestibulum iaculis maximus felis, eu sollicitudin nisl dictum non. Aliquam erat volutpat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi fringilla est eget ultrices tempor. Proin interdum lacus ac sollicitudin eleifend. Duis ac erat non turpis tempor aliquet vitae dignissim dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec eu placerat neque. Sed sed dolor ornare elit consectetur semper nec in ex. Curabitur sit amet orci elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  },
];

export default blogPosts;
